### ISSUE TITLE
Siege of Orgrimmar v2

### ISSUE THREAD

**Issue by wowcamo** [DeadlyBossMods/DBM-MoP#1]
Is this part of DBM supposed to be inside DBM-Pandaria? looked at the toc for it and doesn't seem to have referenced it, maybe trouble with the packager and it got included inside another one by mistake.   The way the file is being served now, it's inside, so it might cause some problems or report being missing when doing those encounters.

**Comment by MysticalOS** [comment]
Looks like another @Stanzilla Typo

he had SiegeOfOrgrimmatV2 in pkgmeta. :D Thanks for report. I'll fix pkgmeta and it'll package correctly. https://github.com/DeadlyBossMods/DBM-MoP/commit/627664fc28f1212344c510040fec4ee03dcdbbec closes #1

**Comment by Stanzilla** [comment]
oops!
