### ISSUE TITLE
Garrosh inaccurate timers

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-MoP#11]
**Describe the bug**
Inaccurate Siege Engineer, Farseer Iron Wolf and Desecrate timers.

**Do you have an error log of what happened?**
https://gist.github.com/Molkree/fef70ae39ab833d02b852fc0889cf161

**Screenshots**
From first pull:
![image](https://user-images.githubusercontent.com/12860284/94326485-c3a43d80-ffac-11ea-810d-290bc2f69fcc.png)

From second pull:
![image](https://user-images.githubusercontent.com/12860284/94326477-be46f300-ffac-11ea-9471-515b6833e312.png)
![image](https://user-images.githubusercontent.com/12860284/94326494-d585e080-ffac-11ea-8ecc-b92812450e10.png)
![image](https://user-images.githubusercontent.com/12860284/94326504-e5052980-ffac-11ea-81f5-e6e83ed220c6.png)
![image](https://user-images.githubusercontent.com/12860284/94326534-1ed63000-ffad-11ea-9204-d07a2d633bda.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
0e7b8680159637eed252a6a256275d47032b2fde

**Was it working in a previous version? If yes, which was the last good one?**
No idea.

**Comment by MysticalOS** [comment]
All issues in initial complaint are fixed. Non mythic now needs review since understanding of how the adds timers work was completely wrong back then (pulls were never this long on any difficulty). Now that it's known they are gradually soft enrage timers, they need full review on remaining 3 difficulties with really long pulls.

**Comment by Molkree** [comment]
![image](https://user-images.githubusercontent.com/12860284/142679558-62e051b1-8c0c-4a7b-b4e3-769e33bb0b1a.png)
![image](https://user-images.githubusercontent.com/12860284/142679592-98a1fd63-f572-40d0-80bc-c58c4f513358.png)
![image](https://user-images.githubusercontent.com/12860284/142679708-1bc5c327-6338-4924-8709-c9c0a0b131d9.png)
![image](https://user-images.githubusercontent.com/12860284/142679944-8f57e21b-c3ff-4df8-b901-0fe942a45c0f.png)
![image](https://user-images.githubusercontent.com/12860284/142680016-7ede0fc1-7fb1-41ec-9cb4-b2b07a7bfa19.png)
![image](https://user-images.githubusercontent.com/12860284/142680111-cd48e44c-f75a-4527-a50a-cfc069c13a6f.png)
[Log](https://gist.github.com/Molkree/1920e5af3e7e844dfb36948aa3f76cdc)
