### ISSUE TITLE
Heart of Fear module uses DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT which isn't present in DBM 8.2.31

### ISSUE THREAD

**Issue by d1r7y** [DeadlyBossMods/DBM-MoP#3]
Message: Interface\AddOns\DBM-HeartofFear\localization.en.lua:52: attempt to index global 'DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT' (a nil value)
Time: Sun Dec 29 01:11:53 2019
Count: 1
Stack: Interface\AddOns\DBM-HeartofFear\localization.en.lua:52: attempt to index global 'DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT' (a nil value)
Interface\AddOns\DBM-HeartofFear\localization.en.lua:52: in main chunk
[C]: in function `LoadAddOn'
Interface\AddOns\DBM-Core\DBM-Core.lua:3931: in function `LoadMod'
Interface\AddOns\DBM-Core\DBM-Core.lua:3878: in function `LoadModsOnDemand'
Interface\AddOns\DBM-Core\DBM-Core.lua:3830: in function `func'
Interface\AddOns\DBM-Core\DBM-Core.lua:1737: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1728>

Locals: L = <table> {
 timers = <table> {
 }
 general = <table> {
 }
 warnings = <table> {
 }
 miscStrings = <table> {
 }
 cats = <table> {
 }
 options = <table> {
 }
}
(*temporary) = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:11924
(*temporary) = <table> {
 timers = <table> {
 }
 general = <table> {
 }
 warnings = <table> {
 }
 miscStrings = <table> {
 }
 cats = <table> {
 }
 options = <table> {
 }
}
(*temporary) = <table> {
 warnCrush = "Show warning for $spell:122774"
 specwarnUnder = "Show special warning when you are under boss"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "122774"
(*temporary) = "Show warning for $spell:122774"
(*temporary) = "attempt to index global 'DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT' (a nil value)"

**Comment by d1r7y** [comment]
It appears that "countdownCrush" isn't referenced anywhere, so removing it solves the problem...

**Comment by MysticalOS** [comment]
I opened heart of fear and can't find any reference to countdownCrush. So I can only assume your mist of pandaria mods are just out of date.

**Comment by d1r7y** [comment]
I downloaded it from here: https://www.curseforge.com/wow/addons/deadly-boss-mods-mop and it says that r131 is the latest.  I just downloaded r131 again and I see countdownCrush referenced on line 52 of DBM-HeartofFear/localization.en.lua.

Is r131 not the latest?

**Comment by d1r7y** [comment]
I see the fix made in the git repo back on November 6, but I don't think there's a corresponding build on https://www.curseforge.com/wow/addons/deadly-boss-mods-mop with that change...

**Comment by MysticalOS** [comment]
Yeah I see the fix was just never pushed to release. earlier today when i looked it up i looked at current source.

**Comment by MysticalOS** [comment]
Closing ticket since I just tagged a new release to get fix to curse download.

**Comment by d1r7y** [comment]
Thanks!
