### ISSUE TITLE
LUA errors when zoning into Heart of Fear in latest version

### ISSUE THREAD

**Issue by raysmith59** [DeadlyBossMods/DBM-MoP#30]
ERROR 1:
1x DBM-HeartofFear\localization.en.lua:21: attempt to index field 'AUTO_ICONS_OPTION_TEXT' (a nil value)
[string "@DBM-HeartofFear\localization.en.lua"]:21: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3500: in function `LoadMod'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3443: in function `LoadModsOnDemand'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3381: in function `func'
[string "@DBM-Core\modules\Scheduler.lua"]:171: in function <DBM-Core\modules\Scheduler.lua:162>

Locals:
L = <table> {
 timers = <table> {
 }
 general = <table> {
 }
 warnings = <table> {
 }
 miscStrings = <table> {
 }
 cats = <table> {
 }
 options = <table> {
 }
}
(*temporary) = <function> defined @DBM-Core\modules\objects\Localization.lua:69
(*temporary) = <table> {
 timers = <table> {
 }
 general = <table> {
 }
 warnings = <table> {
 }
 miscStrings = <table> {
 }
 cats = <table> {
 }
 options = <table> {
 }
}
(*temporary) = <table> {
 warnEchoDown = "Announce when an Echo is defeated"
 specwarnPlatform = "Show special warning when boss changes platforms"
 ArrowOnAttenuation = "Show DBM Arrow during $spell:127834 to indicate which direction to move"
 specwarnAttenuation = "Show special announce for $spell:127834"
 warnEcho = "Announce when an Echo spawns"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "127834"
(*temporary) = "Show special announce for $spell:127834"
(*temporary) = "attempt to index field 'AUTO_ICONS_OPTION_TEXT' (a nil value)"

ERROR 2:
1x DBM-Core\DBM-Core-b1468f5.lua:10536: table index is nil
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:10536: in function `RegisterKill'
[string "@DBM-HeartofFear\Zorlok.lua"]:9: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3500: in function `LoadMod'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3443: in function `LoadModsOnDemand'
[string "@DBM-Core\DBM-Core-b1468f5.lua"]:3381: in function `func'
[string "@DBM-Core\modules\Scheduler.lua"]:171: in function <DBM-Core\modules\Scheduler.lua:162>

Locals:
self = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 instanceId = 330
 modelId = 42807
 SyncThreshold = 8
 numBoss = 1
 modId = "DBM-HeartofFear"
 groupSpells = <table> {
 }
 zones = <table> {
 }
 revision = 20220116041948
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "745"
 combatInfo = <table> {
 }
 encounterId = 1507
 creatureId = 62980
 addon = <table> {
 }
 groupOptions = <table> {
 }
 specwarns = <table> {
 }
 iconRestore = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
msgType = "yell"
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
v = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "table index is nil"
select = <function> defined =[C]:-1
type = <function> defined =[C]:-1

**Comment by MysticalOS** [comment]
Right, I forgot to tag all the old modules again with the renames of latest version, I'll do that now, which will fix this issue.
