### ISSUE TITLE
MOP remix timer errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-MoP#51]
**Describe the bug**
1. Remix LFR Terrace of the Endless Spring
2. Remix Heroic Scenario Battle on the High Seas

**Do you have an error log of what happened?**
[transcripts.zip](https://github.com/DeadlyBossMods/DBM-MoP/files/15451009/transcripts.zip)

**Screenshots**
![WoWScrnShot_052724_121133](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/095472f5-9ce8-43c3-9e10-bff94a69e495)
![WoWScrnShot_052724_123851](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/f672d799-dbd6-4bd9-bc5a-f47f29b917ae)

**Which version of DeadlyBossMods are you using?**
MoP r171

**Comment by Molkree** [comment]
I'll add some as well
LFR SoO Sha of Pride
```
"<79.25 00:32:24> [DBM_Debug] Timer Self-Reflection(Timer144800next) refreshed before expired. Remaining time is : 24.6. Please report this bug#2",
...
"<79.25 00:32:24> [DBM_Debug] Timer Corrupted Prison(Timer144574next) refreshed before expired. Remaining time is : 52.6. Please report this bug#2",
...
"<88.26 00:32:33> [DBM_Debug] Timer Manifestation of Pride(Timerej8262next) refreshed before expired. Remaining time is : 50.6. Please report this bug#2",
```

[Transcriptor.zip](https://github.com/DeadlyBossMods/DBM-MoP/files/15475816/Transcriptor.zip)
