### ISSUE TITLE
Remix LFR SoO Galakras

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-MoP#55]
**Describe the bug**

![image](https://github.com/DeadlyBossMods/DBM-MoP/assets/12860284/dd4081da-21da-49e6-8552-06d8956afaf8)

```
"<114.47 23:41:50> [DBM_Debug] Timer Foot Soldiers (4)(Timer-8553nextcount) (Stage 1) refreshed before expired. Remaining time is : 54.4. Please report this bug#2",
```

**Do you have an error log of what happened?**

[Transcriptor.zip](https://github.com/DeadlyBossMods/DBM-MoP/files/15505182/Transcriptor.zip)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
1344ea41443f72c64a17c036e146bd61a0c8f18e

**Was it working in a previous version? If yes, which was the last good one?**
Dunno

**Additional context**
Might be broken after 1344ea41443f72c64a17c036e146bd61a0c8f18e? It touched this encounter.

**Comment by MysticalOS** [comment]
use alpha. this was fixed already

**Comment by Molkree** [comment]
I indicated in my report that I use alpha, exactly the commit where it's supposed to be fixed

**Comment by MysticalOS** [comment]
Do you play with nameplates off? this log is actually useless, sadly.
