### ISSUE TITLE
Remix LFR Throne of Thunder timer error due to fast phasing

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-MoP#57]
**Describe the bug**
Council of Elders timer error due to phasing quickly

**Do you have an error log of what happened?**
[LFR ToT wing 1.zip](https://github.com/user-attachments/files/15519603/LFR.ToT.wing.1.zip)

**Screenshots**
![WoWScrnShot_060124_021108](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/92202562-a133-4923-9a52-103b6527194b)

**Which version of DeadlyBossMods are you using?**
Raids-MoP-r171-5 alpha

**Comment by MysticalOS** [comment]
This won't be fixable due to fact that the original timer is unknown (frostbite timer inherits Cd of another timer when bosses change power, so we don't know which timer is too long for remix with rapid phasing). The boss needs to live several minutes to get enough data to fix this, which likely will NEVER happen in remix. i'll leave issue open but as low prio won't fix (since it's not possible to)

**Comment by jungheeMW** [comment]
Ran the Council of Elders on retail (non-remix), Heroic, solo. Here is a log, with additional screenshots if necessary.

[heroic tot solo.zip](https://github.com/user-attachments/files/15536628/heroic.tot.solo.zip)

![WoWScrnShot_060324_235453](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/e7a501da-240a-469f-a7db-b3c1d2130174)
![WoWScrnShot_060324_235522](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/b8e3d155-bfc1-42f2-a9de-f69d4d7bd28f)
![WoWScrnShot_060324_235555](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/105c7bb2-59a3-4657-9e96-df102d21c350)
![WoWScrnShot_060324_235627](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/323f33de-f6ca-411b-b1f3-e16a9663ee3f)

**Comment by MysticalOS** [comment]
Sadly this solo never saw a single biting cold cast, so it doesn't help with the original issue at all

**Comment by jungheeMW** [comment]
The original error is also a Frostbite timer error though, not Biting Cold.

The Quicksand one I don't get, because I thought you had adjusted it [here](https://github.com/DeadlyBossMods/DBM-MoP/commit/b3d92e9cbc5344ce8ffa36deb7fff9ff00fea1f0#diff-e29f654c1c4a02dc9a2303be3ebb98084c7b0bb0b0d53ab4b7496099409347cd) already?
