### ISSUE TITLE
Remix Normal Heart of Fear - Garalon Spam and Amber Shaper Un'sok timer error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-MoP#59]
**Describe the bug**
1. When a raid member is sitting directly under Garalon for an extended period of time, error messages get spammed
2. Amber Shape Un'sok errors when played is transformed into Mutated Construct

**Do you have an error log of what happened?**
[remix normal heart of fear.zip](https://github.com/user-attachments/files/15523948/remix.normal.heart.of.fear.zip)

**Screenshots**
![WoWScrnShot_060224_100055](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/8afed6fc-dc2d-4291-bebb-7df74e53433a)
![WoWScrnShot_060224_100102](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/38a6dc7d-ae59-4be2-a80d-b56d5c4d48db)
![WoWScrnShot_060224_101034](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/328166a0-43ba-4090-8779-4e9520120fd6)
![WoWScrnShot_060224_101049](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/5235f55e-f7dd-4ee2-a59e-baca399edd57)
![WoWScrnShot_060224_101115](https://github.com/DeadlyBossMods/DBM-MoP/assets/134947146/4790db5e-1c42-4a41-bbee-0f4642adec85)

**Which version of DeadlyBossMods are you using?**
MoP r172

**Comment by MysticalOS** [comment]
for crush, that timer always broke if plaeyrs triggered extras, not much can be done about that. under normal circumstances players standing there was a wipe, remix is just a special case where people can live ignoring mechanic

**Comment by jungheeMW** [comment]
Ah okay, thank you.
