### ISSUE TITLE
Malkorok timer

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-MoP#8]
**Describe the bug**
Incorrect timer in Malkorok encounter.

**Do you have an error log of what happened?**
https://gist.github.com/Molkree/3d3f00c00646698993069a974ed5f738

**Screenshots**
![image](https://user-images.githubusercontent.com/12860284/94309568-f2a4ba00-ff80-11ea-93ff-f4615caae27e.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
r137-6-g0e7b868

**Was it working in a previous version? If yes, which was the last good one?**
No idea.

**Comment by QartemisT** [comment]
Should be fixed as of #16.
